use soroban_sdk::{BytesN, Env, Vec};

use crate::VerificationKey;

// VK bytes are generated by `smol-fe/scripts/gen_risc0_groth16_vk.mjs`.
include!("vk_constants.rs");

pub fn risc0_verifying_key(env: &Env) -> VerificationKey {
    let mut ic: Vec<BytesN<64>> = Vec::new(env);
    for point in VK_IC.iter() {
        ic.push_back(BytesN::from_array(env, point));
    }

    VerificationKey {
        alpha_g1: BytesN::from_array(env, &VK_ALPHA_G1),
        beta_g2: BytesN::from_array(env, &VK_BETA_G2),
        gamma_g2: BytesN::from_array(env, &VK_GAMMA_G2),
        delta_g2: BytesN::from_array(env, &VK_DELTA_G2),
        ic,
    }
}
