<script lang="ts">
    import { FARM_SAMPLE_PROOFS, type FarmSampleProof } from "../../../data/farmSampleProofs";
    import { TIER_CONFIG } from "./zkTypes";
    import { verifyProofLocally } from "./zkProof";

    let copiedId = $state<string | null>(null);
    let verifyingId = $state<string | null>(null);
    let verifyResults = $state<Record<string, { valid: boolean; ms: number; error?: string }>>({});

    function tierIcon(tierIndex: number): string {
        return TIER_CONFIG[tierIndex]?.icon ?? "🌱";
    }

    function tierColor(tierIndex: number): string {
        return TIER_CONFIG[tierIndex]?.color ?? "#86efac";
    }

    async function copyJson(sample: FarmSampleProof) {
        const payload = {
            proof: sample.proof,
            publicSignals: sample.publicSignals,
        };
        try {
            await navigator.clipboard.writeText(JSON.stringify(payload, null, 2));
        } catch {
            const ta = document.createElement("textarea");
            ta.value = JSON.stringify(payload, null, 2);
            ta.style.position = "fixed";
            ta.style.opacity = "0";
            document.body.appendChild(ta);
            ta.select();
            document.execCommand("copy");
            document.body.removeChild(ta);
        }
        copiedId = sample.id;
        setTimeout(() => { if (copiedId === sample.id) copiedId = null; }, 2000);
    }

    async function verifyProof(sample: FarmSampleProof) {
        verifyingId = sample.id;
        // Clear any previous result for this proof
        const prev = { ...verifyResults };
        delete prev[sample.id];
        verifyResults = prev;

        const start = performance.now();
        try {
            const valid = await verifyProofLocally(sample.proof, sample.publicSignals);
            const ms = Math.round(performance.now() - start);
            verifyResults = { ...verifyResults, [sample.id]: { valid, ms } };
        } catch (err: any) {
            const ms = Math.round(performance.now() - start);
            verifyResults = {
                ...verifyResults,
                [sample.id]: {
                    valid: false,
                    ms,
                    error: err?.message || "Verification failed",
                },
            };
        } finally {
            verifyingId = null;
        }
    }
</script>

<section class="sample-proofs">
    <h2 class="sp-heading">Sample Proofs</h2>
    <p class="sp-description">
        Real Groth16 BN254 proofs generated by the tier_proof circuit.
        Verification runs entirely in your browser — no server calls.
    </p>

    <div class="sp-grid">
        {#each FARM_SAMPLE_PROOFS as sample (sample.id)}
            {@const result = verifyResults[sample.id]}
            <div
                class="sp-card"
                class:sp-card--invalid={!sample.isValid}
                style="--tier-color: {tierColor(sample.tierIndex)}"
            >
                <div class="sp-card-header">
                    <span class="sp-card-icon">{tierIcon(sample.tierIndex)}</span>
                    <div class="sp-card-titles">
                        <h3 class="sp-card-label">{sample.label}</h3>
                        <span class="sp-card-tier">Tier: {sample.tier}</span>
                    </div>
                    {#if !sample.isValid}
                        <span class="sp-badge sp-badge--invalid">Invalid</span>
                    {:else if sample.isEdgeCase}
                        <span class="sp-badge sp-badge--edge">Edge Case</span>
                    {/if}
                </div>

                <p class="sp-card-desc">{sample.description}</p>

                {#if result}
                    <p
                        class="sp-card-result"
                        class:sp-card-result--pass={result.valid}
                        class:sp-card-result--fail={!result.valid}
                        aria-live="polite"
                    >
                        {#if result.valid}
                            Proof verified in {result.ms}ms
                        {:else if result.error}
                            Proof invalid — {result.error}
                        {:else}
                            Proof invalid — pairing check failed
                        {/if}
                    </p>
                {/if}

                <div class="sp-card-actions">
                    <button
                        class="sp-btn sp-btn--verify"
                        disabled={verifyingId === sample.id}
                        onclick={() => verifyProof(sample)}
                    >
                        {#if verifyingId === sample.id}
                            Verifying…
                        {:else if result?.valid}
                            Re-verify
                        {:else}
                            Verify
                        {/if}
                    </button>

                    <button
                        class="sp-btn sp-btn--copy"
                        onclick={() => copyJson(sample)}
                    >
                        {#if copiedId === sample.id}
                            Copied!
                        {:else}
                            Copy JSON
                        {/if}
                    </button>
                </div>
            </div>
        {/each}
    </div>
</section>

<style>
    .sample-proofs {
        width: 100%;
        max-width: 1100px;
        margin: 0 auto;
        padding: 48px 20px 64px;
    }

    .sp-heading {
        font-family: "Inter", system-ui, sans-serif;
        font-size: 28px;
        font-weight: 800;
        letter-spacing: -0.5px;
        color: #e8f2ff;
        margin: 0 0 8px;
    }

    .sp-description {
        font-family: "Inter", system-ui, sans-serif;
        font-size: 14px;
        color: #8899aa;
        margin: 0 0 32px;
        line-height: 1.5;
    }

    .sp-grid {
        display: grid;
        grid-template-columns: 1fr;
        gap: 16px;
    }

    @media (min-width: 640px) {
        .sp-grid {
            grid-template-columns: repeat(2, 1fr);
        }
    }

    @media (min-width: 1024px) {
        .sp-grid {
            grid-template-columns: repeat(3, 1fr);
        }
    }

    .sp-card {
        background: rgba(10, 18, 30, 0.8);
        border: 1px solid rgba(255, 255, 255, 0.08);
        border-radius: 12px;
        padding: 20px;
        display: flex;
        flex-direction: column;
        gap: 12px;
        transition: border-color 0.2s, box-shadow 0.2s;
    }

    .sp-card:hover {
        border-color: var(--tier-color, rgba(255, 255, 255, 0.15));
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.3);
    }

    .sp-card--invalid {
        border-color: rgba(239, 68, 68, 0.25);
    }

    .sp-card-header {
        display: flex;
        align-items: center;
        gap: 10px;
    }

    .sp-card-icon {
        font-size: 24px;
        line-height: 1;
    }

    .sp-card-titles {
        flex: 1;
        min-width: 0;
    }

    .sp-card-label {
        font-family: "Inter", system-ui, sans-serif;
        font-size: 16px;
        font-weight: 700;
        color: #e8f2ff;
        margin: 0;
        line-height: 1.2;
    }

    .sp-card-tier {
        font-family: "Inter", system-ui, sans-serif;
        font-size: 11px;
        color: var(--tier-color, #8899aa);
        letter-spacing: 0.5px;
    }

    .sp-badge {
        font-family: "Inter", system-ui, sans-serif;
        font-size: 10px;
        font-weight: 600;
        text-transform: uppercase;
        letter-spacing: 0.5px;
        padding: 3px 8px;
        border-radius: 6px;
        white-space: nowrap;
    }

    .sp-badge--invalid {
        background: rgba(239, 68, 68, 0.15);
        color: #f87171;
        border: 1px solid rgba(239, 68, 68, 0.3);
    }

    .sp-badge--edge {
        background: rgba(250, 204, 21, 0.1);
        color: #facc15;
        border: 1px solid rgba(250, 204, 21, 0.25);
    }

    .sp-card-desc {
        font-family: "Inter", system-ui, sans-serif;
        font-size: 13px;
        color: #8899aa;
        line-height: 1.5;
        margin: 0;
    }

    .sp-card-result {
        font-family: "Inter", system-ui, sans-serif;
        font-size: 12px;
        border-radius: 8px;
        padding: 8px 12px;
        margin: 0;
        line-height: 1.4;
    }

    .sp-card-result--pass {
        color: #86efac;
        background: rgba(34, 197, 94, 0.08);
        border: 1px solid rgba(34, 197, 94, 0.2);
    }

    .sp-card-result--fail {
        color: #fca5a5;
        background: rgba(239, 68, 68, 0.08);
        border: 1px solid rgba(239, 68, 68, 0.2);
    }

    .sp-card-actions {
        display: flex;
        gap: 8px;
        margin-top: auto;
        padding-top: 8px;
    }

    .sp-btn {
        font-family: "Inter", system-ui, sans-serif;
        font-size: 12px;
        font-weight: 600;
        padding: 8px 14px;
        border-radius: 8px;
        border: 1px solid rgba(255, 255, 255, 0.12);
        cursor: pointer;
        transition: background 0.15s, border-color 0.15s;
        white-space: nowrap;
    }

    .sp-btn:disabled {
        opacity: 0.5;
        cursor: not-allowed;
    }

    .sp-btn--verify {
        background: rgba(122, 255, 207, 0.1);
        color: #7affcf;
        border-color: rgba(122, 255, 207, 0.25);
    }

    .sp-btn--verify:hover:not(:disabled) {
        background: rgba(122, 255, 207, 0.2);
        border-color: rgba(122, 255, 207, 0.4);
    }

    .sp-btn--copy {
        background: rgba(255, 255, 255, 0.05);
        color: #b6c8dd;
    }

    .sp-btn--copy:hover {
        background: rgba(255, 255, 255, 0.1);
        border-color: rgba(255, 255, 255, 0.2);
    }
</style>
